export default [
	{
		ignores: ["**/*.min.js", "vendor/**"],
	},
	{
		files: [
			"admin/assets/js/**/*.js",
			"frontend/js/*.js",
		],
		languageOptions: {
			ecmaVersion: 2020,
			sourceType: "script",
			globals: {
				window: "readonly",
				document: "readonly",
				console: "readonly",
				setTimeout: "readonly",
				setInterval: "readonly",
				clearInterval: "readonly",
				clearTimeout: "readonly",
				fetch: "readonly",
				FormData: "readonly",
				URLSearchParams: "readonly",
				URL: "readonly",
				HTMLElement: "readonly",
				Event: "readonly",
				navigator: "readonly",
				location: "readonly",
				history: "readonly",
				localStorage: "readonly",
				sessionStorage: "readonly",
				MutationObserver: "readonly",
				IntersectionObserver: "readonly",
				jQuery: "readonly",
				wp: "readonly",
				FAZ: "writable",
				fazAdmin: "readonly",
				fazConfig: "readonly",
				fazGcm: "readonly",
				fazDashboard: "readonly",
				fazBanner: "readonly",
				fazCookies: "readonly",
				__tcfapi: "writable",
			},
		},
		rules: {
			"no-unused-vars": ["warn", { "varsIgnorePattern": "^_", "argsIgnorePattern": "^_", "caughtErrorsIgnorePattern": "^_" }],
			"eqeqeq": "warn",
			"no-redeclare": "warn",
			"no-constant-condition": "warn",
			"no-empty": "warn",
			"no-unreachable": "warn",
			"no-dupe-keys": "warn",
			"no-duplicate-case": "warn",
			"no-irregular-whitespace": "warn",
		},
	},
];
